config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  namespace :api do
    resources :guns, only: [:index]
    resources :gun_ranges, only: [:index]
  end

  get '/feed', to: 'feed#show', as: 'feed'
  get '/more', to: 'more#show', as: 'more'
  resources :gun_ranges, only: [:index]

  resources :users, only: [:show] do
    resources :targets
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gun.rb
class Gun < ApplicationRecord
  has_many :targets

  enum type: [:handgun, :rifle, :shotgun]
end

app/models/gun_range.rb
class GunRange < ApplicationRecord
  has_many :targets


  def image_path
    "ranges/#{name.parameterize.underscore}.png"
  end
end

app/models/shot.rb
class Shot < ApplicationRecord
  belongs_to :target
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user
  belongs_to :gun
  belongs_to :gun_range
  has_many :shots

  mount_uploader :image, TargetUploader


  validates :image, presence: true

  def processed_image_path
    image.url.sub("target.jpg", "target_processed.jpg")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :targets
end

app/controllers/api/almond_controller.rb
class Api::AlmondController < ApplicationController

  def question_1
    # params[]
  end
end

app/controllers/api/gun_ranges_controller.rb
class Api::GunRangesController < ApplicationController

  def index
    if params[:shooter]
      shooter = User.where("name LIKE ?", "%#{params[:shooter]}%").first
      @gun_ranges = []
      if shooter
        target = shooter.targets.last
        if target
          @gun_ranges = [target.gun_range]
        end
      end
    else
      @gun_ranges = GunRange.all
    end
  end
end

app/controllers/api/guns_controller.rb
class Api::GunsController < ApplicationController

  def index
    @guns = Gun.where("name LIKE ?", "%#{params[:term]}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    feed_path(resource)
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  before_action :authenticate_user!

  def show
    @targets = Target.all
  end
end

app/controllers/gun_ranges_controller.rb
class GunRangesController < ApplicationController

  def index
    @gun_ranges = GunRange.first(10)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to user_path(current_user)
    end
  end
end

app/controllers/more_controller.rb
class MoreController < ApplicationController
  def show
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :authenticate_user!

  def new
    @target = Target.new
  end

  def show
    @target = Target.find(params[:id])
  end

  def create
    @gun = Gun.find_by(name: params[:target][:gun_id])
    @range = GunRange.find_by(name: params[:target][:gun_range_id])

    @target = current_user.targets.build(sanitized_params)
    @target.gun = @gun
    @target.gun_range = @range

    @target.save!

    root_dir = Rails.root.to_s

    Kernel.system("python #{root_dir}/image_processing/process.py #{@target.id}")
    redirect_to user_target_path(current_user, @target)
  end

  private

  def sanitized_params
    params.require(:target).permit(:image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @gun_ranges = GunRange.first(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/feed/show.html.erb
<div class="annie-nf">
  <% @targets.each do |target| %>
    <div class="annie-nf-item">
      <%= image_tag target.processed_image_path, class: 'img-fluid' %>
      <div class="annie-nf-lower row">
        <%= gravatar_image_tag(target.user.email, class: "col-xs-2") %>
        <div class="col-xs-10 annie-nf-lower-content">
          <a href="<%= user_target_path(current_user, target) %>">
          <b class="annie-nf-user-name"><%= target.user.name %></b>
          <p class="annie-nf-range-name"><%= target.gun_range.name %></p>
          <p class="annie-nf-gun-name"><%= target.gun.name %></p>
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/gun_ranges/index.html.erb
<% @gun_ranges.each do |gun_range| %>
  <div>
    <%= image_tag gun_range.image_path, class: "img-fluid" %>
    <p><%= gun_range.name %></p>
  </div>
<% end %>
<br>
<br>

app/views/home/index.html.erb
<div class="annie-home">
  <h1>Annie</h1>
  <%= image_tag "gun_logo.png", class: "annie-home-logo" %>
  <%= link_to "Sign In", new_user_session_path, class: 'btn btn-secondary' %>
  <%= link_to "create new account", new_user_registration_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Annie</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Smokum" rel="stylesheet">
  </head>

  <body>
    <div class="container annie_<%= controller.controller_name + '_' + controller.action_name%>">
      <div class='flow-loading hidden'>
        <%= image_tag "loading_animation.svg", style: 'margin: 0 auto'%>
        <p><b>Processing Image...</b></p>
      </div>
      <%= yield %>
      <% if user_signed_in? %>
        <nav class="navbar fixed-bottom navbar-light bg-faded annie-navbar">
          <a class="navbar-link" href="/feed"><%= image_tag 'feed_logo.png', class: "img-fluid" %></a>
          <a class="navbar-link" href="/gun_ranges"><%= image_tag 'globe_logo.png' %></a>
          <%= link_to image_tag('target_logo.png'), new_user_target_path(current_user), class: "navbar-link" %>
          <%= link_to image_tag('user_profile_icon.png'), user_path(current_user), class: "navbar-link" %>
          <a class="navbar-link" href="/more"><%= image_tag('more_logo.png') %></a>
        </nav>
      <% end %>
    </div>
  </body>
</html>

app/views/more/show.html.erb
<br/>
<br/>
<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-warning' %>

app/views/targets/new.html.erb
<div class="js-hidethis">
  <h1>Upload Target</h1>
  <br/>
  <br/>
  <%= form_for [current_user, @target], html: { multipart: true } do |f| %>
    <div class="annie-target-form">
      <%= image_tag 'upload_logo.png', width: '50px', class: 'js-uploadIcon' %>
      <div class="annie-target-check">✔</div>

      <br/>
      <br/>
        <%= f.file_field :image, style: 'display: none', class: 'js-uploadField', required: true %>

      <div class="form-group">
        <%= f.text_field :gun_range_id, placeholder: 'select location', class: "form-control js-gunRangeField", required: true %>
      </div>

      <%= f.text_field :gun_id, placeholder: 'select gun', class: "form-control js-gunField", required: true %>
      <br/>
    </div>


    <%= f.submit 'Save Target', class: 'btn btn-primary js-submit' %>
  <% end %>
</div>

<script type="text/javascript">
  $( function() {
    // function log( message ) {
      // $( ".js-rangeField" ).text( message ).prependTo( "#log" );
      // $( "#log" ).scrollTop( 0 );
    // }
    //

    $('.js-submit').click(function(e) {
      e.preventDefault();
      var $this = $(this);
      $this.unbind('click');
      $('.js-hidethis').hide();
      $('.flow-loading').removeClass('hidden');

      setTimeout(function(){
        $this.click();
      }, 1000);
    });

    var randTime = Math.floor(Math.random() * 500) + 500;

    $('.js-uploadIcon').click(function(e) {
      $('.js-uploadField').click();
    });

    $('.annie-target-check').hide();

    $('.js-uploadField').on('change', function(e) {
      $('.js-uploadIcon').hide();
      $('.annie-target-check').show();
    });

    $(".js-gunField").autocomplete({
      source: function(request, response) {
        $.ajax( {
          url: "/api/guns",
          dataType: "json",
          data: {
            term: request.term
          },
          success: function( data ) {
            response(data['guns']);
          }
        });
      },
      minLength: 2,
      select: function( event, ui ) {
        console.log( "Selected: " + ui.item.value + " aka " + ui.item.id );
      }
    });

    $(".js-gunRangeField").autocomplete({
      source: function(request, response) {
        $.ajax( {
          url: "/api/gun_ranges",
          dataType: "json",
          data: {
            term: request.term
          },
          success: function( data ) {
            response(data['gun_ranges']);
          }
        });
      },
      minLength: 2,
      select: function( event, ui ) {
        console.log( "Selected: " + ui.item.value + " aka " + ui.item.id );
      }
    });
  } );
</script>

app/views/targets/show.html.erb
<%= image_tag(@target.processed_image_path, class: 'img-fluid') %>

<h2>Shot Details</h2>

<p><%= @target.gun.name %></p>
<p><%= @target.gun_range.name %></p>
<p> Shot Count: <%= @target.shots.count %> </p>

<table class="table">
  <thead>
    <th>Shot #</th>
    <th>%H</th>
    <th>%V</th>
  </thead>

  <% @target.shots.each_with_index do |shot, i| %>
    <tr>
      <td><%= i %></td>
      <td><%= (((shot.x_pos - (@target.width.to_f / 2)) / @target.width) * 100).round(2) %>% </td>
      <td><%= (((shot.y_pos - (@target.height.to_f / 2)) / @target.height) * 100).round(2) %>% </td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<div class="annie-user-profile">
  <h1><%= @user.name %></h1>

  <%= gravatar_image_tag(@user.email, class: "annie-user-profile-image") %>

  <h2>My Ranges</h2>
  <div class="annie-gun-ranges">
    <% @gun_ranges.each do |gun_range| %>
      <%= image_tag gun_range.image_path, class: "img-fluid" %>
    <% end %>
  </div>
</div>